import Head from 'next/head'
import About from '../components/03_sections/about'
import Faqs from '../components/03_sections/faqs'
import FullscreenPicture from '../components/03_sections/fullscreenPicture'
import Hero from '../components/03_sections/hero'
import Outtro from '../components/03_sections/outtro'
import Roadmap from '../components/03_sections/roadmap'
import Speakers from '../components/03_sections/speakers'
import Sponsors from '../components/03_sections/sponsors'
import Stories from '../components/03_sections/stories'
import Tracks from '../components/03_sections/tracks'
import styles from '../styles/Home.module.css'
import Image from 'next/image'
import NavBar from '../components/02_molecules/navBar'

import {Element} from 'react-scroll'
import Video from '../components/03_sections/video'
import SponsorInfo from '../components/03_sections/sponsorInfo'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Makeathon 2022</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="assets/blackVioletlarge_logo.png"/>
      </Head>

      <main className={styles.main}>
        <NavBar />
        <Hero id="hero"/>
        <Element name="about"></Element>
        <About />
        <Video />
        {/* <Roadmap /> */}
        {/* <FullscreenPicture /> */}
        {/* <Element name="tracks">
          <Tracks />
        </Element> */}
        {/* <Element name="speakers">
          <Speakers />
        </Element> */}
        <Element name="stories">
          <Stories />
        </Element>
        <Sponsors />
        <SponsorInfo />
        <Element name="faqs">
          <Faqs />
        </Element>
        <Outtro />
      </main>

      <footer className={styles.Footer}>
        <div className={styles.Grid}>
          <div className={styles.Container}>
            <div className={styles.Top}>{"TUM.ai © 2022 "}</div>
            <div className={styles.Middle}>
              <div className={styles.FirstContainer}>
                {"Website by IT & Infrastructure department"}
              </div>
              <div className={styles.SecondContainer}>
                <a href="mailto:contact@tum-ai.com" className={styles.Link}>Contact</a>
                <a className={styles.Link}>Admin</a>
              </div>
              <div className={styles.ThirdContainer}>
                <a href="https://www.tum-ai.com/datenschutz" className={styles.Link}>{"Terms&Security"}</a>
                <a href="https://www.tum-ai.com/impressum" className={styles.Link}>Imprint</a>
              </div>
            </div>
            <div className={styles.Bottom}>
              <a className={styles.SocialWrapper} href="https://www.linkedin.com/company/tum-ai/">
                <Image src={"/assets/linkedIn.svg"} alt={"LinkedIn"} layout="fill" objectFit="cover" />
              </a>
              <a className={styles.SocialWrapper} href="https://www.instagram.com/tum.ai_official/">
                <Image src={"/assets/insta.svg"} alt={"Instagram"} layout="fill" objectFit="cover" />
              </a>
            </div>
          </div>
        </div>
      </footer>
    </div>
  )
}
