import Head from "next/head";
import About from "../components/03_sections/about";
import Faqs from "../components/03_sections/faqs";
import FullscreenPicture from "../components/03_sections/fullscreenPicture";
import Hero from "../components/03_sections/hero";
import Outtro from "../components/03_sections/outtro";
import Roadmap from "../components/03_sections/roadmap";
import Banner from "../components/03_sections/banner";
import Speakers from "../components/03_sections/speakers";
import Sponsors from "../components/03_sections/sponsors";
import PreviousSponsors from "../components/03_sections/previousSponsors";
import Stories from "../components/03_sections/stories";
import Tracks from "../components/03_sections/tracks";
import styles from "../styles/Home.module.css";
import Image from "next/image";
import NavBar from "../components/02_molecules/navBar";

import { Element } from "react-scroll";
import Video from "../components/03_sections/video";
import SponsorInfo from "../components/03_sections/sponsorInfo";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Makeathon 2024</title>
        <meta
          name="description"
          content="Generated by create next app"
        />
        <link
          rel="icon"
          href="assets/blackVioletlarge_logo.png"
        />
      </Head>

      <main className={styles.main}>
        <NavBar />
        <Hero id="hero" />
        <Element name="about"></Element>
        <About />
        <Roadmap />
        <Video />
        <Banner />
        {/*<FullscreenPicture />
        <Element name="tracks">
          <Tracks />
        </Element>*/}
        {/* <Element name="speakers">
          <Speakers />
        </Element> */}
        <Element name="stories">
          <Stories />
        </Element>
        <section className="relative isolate overflow-hidden bg-white px-6 py-24 sm:py-32 lg:px-8">
          <div className="absolute inset-0 -z-10 bg-[radial-gradient(45rem_50rem_at_top,theme(colors.indigo.100),white)] opacity-20" />
          <div className="absolute inset-y-0 right-1/2 -z-10 mr-16 w-[200%] origin-bottom-left skew-x-[-30deg] bg-white shadow-xl shadow-indigo-600/10 ring-1 ring-indigo-50 sm:mr-28 lg:mr-0 xl:mr-16 xl:origin-center" />
          <div className="mx-auto max-w-2xl lg:max-w-4xl">
            <img
              className="mx-auto h-12"
              src={"/assets/Reply-LOGO.jpg"}
              alt=""
            />
            <figure className="mt-10">
              <blockquote className="text-center text-xl font-semibold leading-8 text-gray-900 sm:text-2xl sm:leading-9">
                <p>
                  &quot;We from Reply can&apos;t wait to get
                  to know you during the TUM.ai Makeathon!
                  We are already looking forward to your
                  innovative ideas to solve our challenge.
                  Join us in exploring the forefront of AI
                  innovation as we go deep into the realm of
                  predictive maintenance for enhanced energy
                  efficiency. Harness the power of data from
                  renewable energy systems to minimize
                  downtime, maximize energy output, and
                  enhance operational reliability. Take this
                  opportunity to learn, innovate, and make a
                  tangible impact on the future of renewable
                  energy. Join us and be a part of shaping a
                  sustainable tomorrow!&quot;
                </p>
              </blockquote>
            </figure>
          </div>
        </section>

        <Sponsors />
        <SponsorInfo />
        <Element name="faqs">
          <Faqs />
        </Element>
        <Outtro />
        <PreviousSponsors />
      </main>

      <footer className={styles.Footer}>
        <div className={styles.Grid}>
          <div className={styles.Container}>
            <div className={styles.Top}>
              {"TUM.ai © 2024 "}
            </div>
            <div className={styles.Middle}>
              <div className={styles.FirstContainer}>
                {
                  "Website by Software Development Department"
                }
              </div>
              <div className={styles.SecondContainer}>
                <a
                  href="mailto:contact@tum-ai.com"
                  className={styles.Link}
                >
                  Contact
                </a>
                <a className={styles.Link}>Admin</a>
              </div>
              <div className={styles.ThirdContainer}>
                <a
                  href="https://www.tum-ai.com/data-privacy"
                  className={styles.Link}
                >
                  {"Terms&Security"}
                </a>
                <a
                  href="https://www.tum-ai.com/imprint"
                  className={styles.Link}
                >
                  Imprint
                </a>
              </div>
            </div>
            <div className={styles.Bottom}>
              <a
                className={styles.SocialWrapper}
                href="https://www.linkedin.com/company/tum-ai/"
              >
                <Image
                  src={"/assets/linkedIn.svg"}
                  alt={"LinkedIn"}
                  layout="fill"
                  objectFit="cover"
                />
              </a>
              <a
                className={styles.SocialWrapper}
                href="https://www.instagram.com/tum.ai_official/"
              >
                <Image
                  src={"/assets/insta.svg"}
                  alt={"Instagram"}
                  layout="fill"
                  objectFit="cover"
                />
              </a>
            </div>
          </div>
        </div>
      </footer>
    </div>
  );
}
