import Head from 'next/head'
import About from '../components/03_sections/about'
import FullscreenPicture from '../components/03_sections/fullscreenPicture'
import Hero from '../components/03_sections/hero'
import Roadmap from '../components/03_sections/roadmap'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Makeathon 2022</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Hero />
        <About />
        <Roadmap />
        <FullscreenPicture />
      </main>

      <footer className={styles.footer}>
       
      </footer>
    </div>
  )
}
